const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const context={window:{VARGI_IMAGES:{}}};
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(root,'assets/geography/pack-atlas.js'),'utf8'),context);
vm.runInContext(html.slice(html.indexOf('const ROSTER ='),html.indexOf('const ATHLETE_PROFILE_LINKS ='))+';this.members=ALL_MEMBERS;',context);
const {buildCities}=context.window.VargiAtlas;
assert.ok(!fs.readFileSync(path.join(root,'assets/geography/pack-atlas.js'),'utf8').includes('"data-count"'),'Do not reuse the site counter hook: it replaces child nodes.');
const cities=buildCities(context.members);
assert.equal(cities.length,14);
assert.equal(cities.reduce((sum,c)=>sum+c.members.length,0),20);
assert.equal(cities.find(c=>c.city==='Петрозаводск').members.length,4);
assert.equal(cities.find(c=>c.city==='Мурманск').members.length,4);
assert.equal(cities.find(c=>c.city==='Долгопрудный').members[0].name,'Мария Новоселова');
assert.equal(cities.flatMap(c=>c.members).filter(m=>m.alpha).length,1);
assert.equal(cities.find(c=>c.members.some(m=>m.alpha)).city,'Воронеж');
const sameCity=buildCities([...context.members,{name:'Тест нового участника',city:'Мурманск'}]);
assert.equal(sameCity.find(c=>c.city==='Мурманск').members.length,5);
const newCity=buildCities([...context.members,{name:'Тест нового города',city:'Новый город',mapLocation:{point:[850,300],label:[875,300]}}]);
assert.equal(newCity.length,15);
assert.equal(newCity.find(c=>c.city==='Новый город').members.length,1);
assert.throws(()=>buildCities([...context.members,{name:'Без города'}]),/Missing verified map city/);
assert.throws(()=>buildCities([...context.members,context.members[0]]),/Duplicate map member/);
assert.throws(()=>buildCities([{name:'Некорректная точка',city:'Тест',mapLocation:{point:[9999,0],label:[0,0]}}]),/Invalid point/);
assert.ok(html.includes('@media(prefers-reduced-motion:reduce){.atlas-beacon'));
assert.deepEqual(Array.from(context.members.slice(15,19),m=>m.name),['Андрей Лисов','Андрей Касьяненко','Даниил Махов','Виталий Ильин']);
assert.equal(context.members.find(m=>m.name==='Андрей Касьяненко').rl,'https://russialoppet.ru/athletes/807465/');
console.log('PASS: 20 members / 14 cities; requested expanded roster order; updated RL link; exact wolf counts; new members/cities validated.');
